name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Bunjs
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.26
      - name: Install dependencies
        run: bun install
      - run: bun run build
      - run: bun run test
